elasticsearch:
  host: 43.201.131.126
  port: 9200

spring:
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

  datasource:
    url: jdbc:mysql://database-1.cvrkyws2tbvq.ap-northeast-2.rds.amazonaws.com:3306/seektamDB?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: white
    password: tnsqor1!

  #    url: jdbc:mysql://127.0.0.1:3306/seektam_test?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
  #    username: root
  #    password:

  # url: jdbc:mysql://seektam-test.cmzzaiee3lj2.ap-northeast-2.rds.amazonaws.com:3306/seektam-test?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true

jwt:
  secret: trhiojrthoijrthoijrthoijrthoirttirojhrthoitrhiojrthoijrthoijrthoijrthoirttirojhrthoitrhiojrthoijrthoijrthoijrthoirttirojhrthoi
  accessExpirationTime: 60000
  refreshExpirationTime: 100000

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

oauth:
  kakao:
    client_id: 2203f40d1fca23a63fe58c152ecae620
    redirect_uri: http://localhost:3000
    auth_uri: https://kauth.kakao.com/oauth/token
    authorization_uri: https://kauth.kakao.com/oauth/authorize
    info_uri: https://kapi.kakao.com/v2/user/me
    # https://kauth.kakao.com/oauth/authorize?response_type=code&client_id=f257cf263d8c8b829bfe18bc453c1aa7&redirect_uri=http://localhost:8080

springdoc:
  swagger-ui:
    enabled: true
  version: 'v1'
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  model-and-view-allowed: true
