version: 0.0
os: linux

files:
  - source:  /
    destination: /home/ec2-user/spring-github-action
    overwrite: yes

permissions:
  - object: /
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: scripts/stop.sh
      timeout: 60
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60

# files:
#   - source:  /
#     destination: /home/ubuntu/cicd
#     overwrite: yes

# permissions:
#   - object: /
#     pattern: "**"
#     owner: ubuntu
#     group: ubuntu

# hooks:
#   ApplicationStart:
#     - location: scripts/backend_deploy.sh
#       timeout: 60
#       runas: ubuntu
