version: 0.0
os: linux 

files:
  - source: /
    destination: /home/ubuntu/cicd
    overwrite: yes
file_exists_behavior: OVERWRITE
permissions:
  - object: /
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 60
