version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/cicd
    overwrite: yes

permissions:
  - object: /
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
